//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_FormBase
    {
        public string ComId { get; set; }
        public int ID { get; set; }
        public string FormCode { get; set; }
        public string FormDec { get; set; }
        public string FormTable { get; set; }
        public string FormColumnName { get; set; }
        public string FormAddUrl { get; set; }
        public string FormMangerUrl { get; set; }
        public string FormViewUrl { get; set; }
        public string FormConfirmUser { get; set; }
        public string FormConfirmbranch { get; set; }
        public string FormConfirmRole { get; set; }
        public string FormTip { get; set; }
        public string FormSearchColumn { get; set; }
        public Nullable<int> FormProcessDefinitionID { get; set; }
        public Nullable<int> Formsycount { get; set; }
        public string FormGetSQL { get; set; }
        public Nullable<int> FormDeleted { get; set; }
        public string FormQueryUrl { get; set; }
        public string FormOrder { get; set; }
        public string FormISZC { get; set; }
        public string FormType { get; set; }
        public string WXAPPCode { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
