//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_Menu
    {
        public string ComId { get; set; }
        public int AuthCode { get; set; }
        public string AuthName { get; set; }
        public string AuthDesc { get; set; }
        public int PAuthCode { get; set; }
        public string FileName { get; set; }
        public string Ico { get; set; }
        public int DisplayOrder { get; set; }
        public int AuthLevel { get; set; }
        public string IsUse { get; set; }
        public string IsHasbt { get; set; }
        public string isSys { get; set; }
        public string isMenu { get; set; }
        public string Remark { get; set; }
    }
}
