
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace QJY.Data
{

using System;
    using System.Collections.Generic;
    
public partial class JH_Auth_FormAttchg
{

    public string ComId { get; set; }

    public int id { get; set; }

    public string FileNewName { get; set; }

    public string FileOldName { get; set; }

    public string FileSize { get; set; }

    public string Cruser { get; set; }

    public Nullable<System.DateTime> Crdate { get; set; }

    public string ProcessID { get; set; }

    public string iseffective { get; set; }

    public string FileType { get; set; }

    public string FileUrl { get; set; }

    public Nullable<int> FileGLJLID { get; set; }

}

}
