//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_KS_SJ
    {
        public int ID { get; set; }
        public string SJName { get; set; }
        public string SJType { get; set; }
        public string ZJType { get; set; }
        public Nullable<int> TotalRecord { get; set; }
        public string SJDescribe { get; set; }
        public Nullable<decimal> PassRecord { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<int> KSSC { get; set; }
        public Nullable<int> kcId { get; set; }
    }
}
