//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_DDGL
    {
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
        public string OrderID { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public string Memo { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string PayMethod { get; set; }
        public string trade_no { get; set; }
        public string trade_status { get; set; }
        public Nullable<System.DateTime> trade_time { get; set; }
    }
}
