//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_KS_ST
    {
        public int ID { get; set; }
        public Nullable<int> TKID { get; set; }
        public string KnowLedge { get; set; }
        public string Type { get; set; }
        public Nullable<int> Level { get; set; }
        public string QContent { get; set; }
        public string QAnswer { get; set; }
        public string QAnalyze { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ComId { get; set; }
    }
}
