//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_KS_USERKSItem
    {
        public int ID { get; set; }
        public Nullable<int> UserKSID { get; set; }
        public Nullable<int> STID { get; set; }
        public string Answer { get; set; }
        public Nullable<decimal> Record { get; set; }
        public Nullable<int> SJID { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> ComId { get; set; }
    }
}
