//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_PX_KJGL
    {
        public int ID { get; set; }
        public string KJName { get; set; }
        public string KJDec { get; set; }
        public string KJType { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CHUser { get; set; }
        public Nullable<System.DateTime> CHDate { get; set; }
        public string KJZJR { get; set; }
        public Nullable<int> KJZZType { get; set; }
        public string Files { get; set; }
        public Nullable<int> ComId { get; set; }
        public string CW { get; set; }
        public Nullable<int> FolderID { get; set; }
        public Nullable<int> TotalTime { get; set; }
    }
}
