//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_KS_KSAP
    {
        public int ID { get; set; }
        public string KSName { get; set; }
        public Nullable<int> SJID { get; set; }
        public Nullable<int> KSSC { get; set; }
        public Nullable<int> YCSY { get; set; }
        public Nullable<System.DateTime> KSDate { get; set; }
        public string KSUser { get; set; }
        public string Remark { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Address { get; set; }
        public Nullable<int> ComId { get; set; }
        public string YJTeacher { get; set; }
    }
}
