//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_QYIM_ITEM
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string FromUserName { get; set; }
        public string MsgType { get; set; }
        public string Content { get; set; }
        public string MsgId { get; set; }
        public string Type { get; set; }
        public string UID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string PicUrl { get; set; }
        public string MediaId { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Event { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Status { get; set; }
        public string Sourse { get; set; }
    }
}
