//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_YX_HD_GM
    {
        public string goodscode { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<decimal> zfje { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Files { get; set; }
        public string iscyhd { get; set; }
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<int> hdid { get; set; }
        public Nullable<int> hdmxid { get; set; }
        public Nullable<int> ctrs { get; set; }
        public Nullable<System.DateTime> gmdate { get; set; }
        public string ishx { get; set; }
        public Nullable<System.DateTime> hxtime { get; set; }
        public string hxusename { get; set; }
        public string batchnumber { get; set; }
    }
}
