//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_PX_KCGL
    {
        public int ID { get; set; }
        public string KCName { get; set; }
        public Nullable<int> KCTypeID { get; set; }
        public string KCZJR { get; set; }
        public string KCZJRZC { get; set; }
        public string KSS { get; set; }
        public string KCPXZQ { get; set; }
        public string Remark { get; set; }
        public string SQType { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CHUser { get; set; }
        public Nullable<System.DateTime> CHDate { get; set; }
        public Nullable<int> ComId { get; set; }
        public string KJID { get; set; }
        public string KCFM { get; set; }
    }
}
