//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_DCGL_ITEM
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public Nullable<int> HID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImgUrl { get; set; }
        public string Remark { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string DelUser { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
    }
}
