
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace QJY.Data
{

using System;
    using System.Collections.Generic;
    
public partial class SZHL_KDDY_PZ
{

    public Nullable<int> ComId { get; set; }

    public int ID { get; set; }

    public string KDID { get; set; }

    public string KDName { get; set; }

    public string IsDefault { get; set; }

    public string imageWidth { get; set; }

    public string imageHeight { get; set; }

    public string objects { get; set; }

    public string FontSize { get; set; }

    public string Font { get; set; }

    public string Horizontal { get; set; }

    public string Vertical { get; set; }

    public string KDImg { get; set; }

    public string CRUser { get; set; }

    public Nullable<System.DateTime> CRDate { get; set; }

    public string Remark { get; set; }

}

}
