//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_WTFK
    {
        public int ID { get; set; }
        public Nullable<int> LeiBie { get; set; }
        public string FKContent { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Files { get; set; }
        public Nullable<int> ComId { get; set; }
        public string ZDUser { get; set; }
        public string CLR { get; set; }
        public Nullable<int> intProcessStanceid { get; set; }
        public string CLContent { get; set; }
        public Nullable<System.DateTime> CLDate { get; set; }
        public string ZDR { get; set; }
        public Nullable<int> CLStatus { get; set; }
    }
}
