//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_HelpMenu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> PID { get; set; }
        public string Title { get; set; }
        public string HelpContent { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> ComId { get; set; }
        public string CRUserName { get; set; }
        public string Files { get; set; }
        public string Remark { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public string MenuChapter { get; set; }
    }
}
