//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_CHAT_MSG
    {
        public int ID { get; set; }
        public int ComId { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public int MsgContentType { get; set; }
        public string MsgContent { get; set; }
        public System.DateTime CRDate { get; set; }
        public int IsReceived { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public int FromUserDeleteFlag { get; set; }
        public Nullable<System.DateTime> FromUserDeleteTime { get; set; }
        public int ToUserDeleteFlag { get; set; }
        public Nullable<System.DateTime> ToUserDeleteTime { get; set; }
        public int ConverId { get; set; }
    }
}
