
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace QJY.Data
{

using System;
    using System.Collections.Generic;
    
public partial class SZHL_KDDY_CYDZ
{

    public Nullable<int> ComId { get; set; }

    public int ID { get; set; }

    public string sendUser { get; set; }

    public string sendTel { get; set; }

    public string sendHomePhone { get; set; }

    public string sendCompany { get; set; }

    public string sendAddress { get; set; }

    public string sendProvince { get; set; }

    public string sendCity { get; set; }

    public string sendCounty { get; set; }

    public string CRUser { get; set; }

    public Nullable<System.DateTime> CRDate { get; set; }

}

}
